# Credentials in ~/.crowdin.yml
# Or with env variable
# "api_token_env" : CROWDIN_API_TOKEN

project_id: "849812"
base_path: "."
base_url: "https://api.crowdin.com"
preserve_hierarchy: true

files:
  - source: "/docs/*.md"
    translation: "/docs/%osx_locale%/%original_file_name%"
    skip_untranslated_files: false
    export_only_approved: false
    content_segmentation: 0
